name: productive
description: "Productive Flutter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.6.7
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  pinput: any
  google_mobile_ads: ^4.0.0
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  equatable: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/create_new_password/
    - assets/icons/
    - assets/icons/calendar/
    - assets/icons/bnb/
    - assets/icons/forgot_password/
    - assets/images/
    - assets/icons/expanse/

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/l10n
  preferred-supported-locales:
    - en
  use-deferred-loading: true

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Light.ttf
        - asset: assets/fonts/Barlow-LightItalic.ttf
        - asset: assets/fonts/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow-ThinItalic.ttf
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
        - asset: assets/fonts/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow-MediumItalic.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow-SemiBoldItalic.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow-BoldItalic.ttf
        - asset: assets/fonts/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow-ExtraBoldItalic.ttf
        - asset: assets/fonts/Barlow-Black.ttf
        - asset: assets/fonts/Barlow-BlackItalic.ttf