name: productive
description: "Productive Flutter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner:
  build_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/logo/
  - assets/fonts/
  - assets/icons/
  - assets/images/
  - assets/images/onboarding_logo.png
  - assets/icons/global/
  - assets/icons/tasks/
  - assets/icons/autenfication/
  - assets/icons/drawer/
  - assets/icons/onBording/
  - assets/icons/upcoming/
  - assets/icons/all/
  - assets/icons/modal/
  - assets/icons/note/
  - assets/icons/create_task/

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/l10n
  preferred-supported-locales:
    - en
  use-deferred-loading: true
